Repository carcutter/carcutter-api-samples, pull requests merged in 2021-11, with the labels that each got.

#14 fix: refer to API
  README.md
Labels: bug

#15 docs: duplicated readme
  README copy.md
Labels: documentation

#13 feat: partly implemented the best feature
  feature1.md
Labels: enhancement
